[package]
name = "cvctl"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]
description = "Cervus Control"
license = "MIT"
repository = "https://github.com/cervus-v/cervus"

[dependencies]
wasm-core = { version = "0.2.15", features = ["trans"]}
libc = "0.2"
